// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.3
// source: rpc/daemon/service.proto

package daemon

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RestartRequest is the request message for restarting the daemon.
type RestartRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// force indicates whether to force restart even if the daemon is busy.
	// (default: false)
	Force         bool `protobuf:"varint,1,opt,name=force,proto3" json:"force,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestartRequest) Reset() {
	*x = RestartRequest{}
	mi := &file_rpc_daemon_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestartRequest) ProtoMessage() {}

func (x *RestartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_daemon_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestartRequest.ProtoReflect.Descriptor instead.
func (*RestartRequest) Descriptor() ([]byte, []int) {
	return file_rpc_daemon_service_proto_rawDescGZIP(), []int{0}
}

func (x *RestartRequest) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

// RestartResponse is the response message after restarting the daemon.
type RestartResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// message contains a status message about the restart operation.
	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	// restarted_at contains the timestamp when the daemon was restarted (RFC3339 format).
	RestartedAt   string `protobuf:"bytes,2,opt,name=restarted_at,json=restartedAt,proto3" json:"restarted_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestartResponse) Reset() {
	*x = RestartResponse{}
	mi := &file_rpc_daemon_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestartResponse) ProtoMessage() {}

func (x *RestartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_daemon_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestartResponse.ProtoReflect.Descriptor instead.
func (*RestartResponse) Descriptor() ([]byte, []int) {
	return file_rpc_daemon_service_proto_rawDescGZIP(), []int{1}
}

func (x *RestartResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RestartResponse) GetRestartedAt() string {
	if x != nil {
		return x.RestartedAt
	}
	return ""
}

// StatusRequest is the request message for getting daemon status.
type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_rpc_daemon_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_daemon_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_rpc_daemon_service_proto_rawDescGZIP(), []int{2}
}

// StatusResponse is the response message with daemon status.
type StatusResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// running indicates if the strategy runner is currently running.
	Running bool `protobuf:"varint,1,opt,name=running,proto3" json:"running,omitempty"`
	// strategy_file is the path to the currently active strategy file.
	StrategyFile string `protobuf:"bytes,2,opt,name=strategy_file,json=strategyFile,proto3" json:"strategy_file,omitempty"`
	// active_queues is the number of active NFQUEUE rules.
	ActiveQueues int32 `protobuf:"varint,3,opt,name=active_queues,json=activeQueues,proto3" json:"active_queues,omitempty"`
	// active_processes is the number of running nfqws processes.
	ActiveProcesses int32 `protobuf:"varint,4,opt,name=active_processes,json=activeProcesses,proto3" json:"active_processes,omitempty"`
	// firewall_backend is the firewall backend being used (nftables or iptables).
	FirewallBackend string `protobuf:"bytes,5,opt,name=firewall_backend,json=firewallBackend,proto3" json:"firewall_backend,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_rpc_daemon_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_daemon_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_rpc_daemon_service_proto_rawDescGZIP(), []int{3}
}

func (x *StatusResponse) GetRunning() bool {
	if x != nil {
		return x.Running
	}
	return false
}

func (x *StatusResponse) GetStrategyFile() string {
	if x != nil {
		return x.StrategyFile
	}
	return ""
}

func (x *StatusResponse) GetActiveQueues() int32 {
	if x != nil {
		return x.ActiveQueues
	}
	return 0
}

func (x *StatusResponse) GetActiveProcesses() int32 {
	if x != nil {
		return x.ActiveProcesses
	}
	return 0
}

func (x *StatusResponse) GetFirewallBackend() string {
	if x != nil {
		return x.FirewallBackend
	}
	return ""
}

var File_rpc_daemon_service_proto protoreflect.FileDescriptor

const file_rpc_daemon_service_proto_rawDesc = "" +
	"\n" +
	"\x18rpc/daemon/service.proto\x12\x06daemon\"&\n" +
	"\x0eRestartRequest\x12\x14\n" +
	"\x05force\x18\x01 \x01(\bR\x05force\"N\n" +
	"\x0fRestartResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12!\n" +
	"\frestarted_at\x18\x02 \x01(\tR\vrestartedAt\"\x0f\n" +
	"\rStatusRequest\"\xca\x01\n" +
	"\x0eStatusResponse\x12\x18\n" +
	"\arunning\x18\x01 \x01(\bR\arunning\x12#\n" +
	"\rstrategy_file\x18\x02 \x01(\tR\fstrategyFile\x12#\n" +
	"\ractive_queues\x18\x03 \x01(\x05R\factiveQueues\x12)\n" +
	"\x10active_processes\x18\x04 \x01(\x05R\x0factiveProcesses\x12)\n" +
	"\x10firewall_backend\x18\x05 \x01(\tR\x0ffirewallBackend2\x86\x01\n" +
	"\fZapretDaemon\x12:\n" +
	"\aRestart\x12\x16.daemon.RestartRequest\x1a\x17.daemon.RestartResponse\x12:\n" +
	"\tGetStatus\x12\x15.daemon.StatusRequest\x1a\x16.daemon.StatusResponseB=Z;github.com/Sergeydigl3/zapret-discord-youtube-ng/rpc/daemonb\x06proto3"

var (
	file_rpc_daemon_service_proto_rawDescOnce sync.Once
	file_rpc_daemon_service_proto_rawDescData []byte
)

func file_rpc_daemon_service_proto_rawDescGZIP() []byte {
	file_rpc_daemon_service_proto_rawDescOnce.Do(func() {
		file_rpc_daemon_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_daemon_service_proto_rawDesc), len(file_rpc_daemon_service_proto_rawDesc)))
	})
	return file_rpc_daemon_service_proto_rawDescData
}

var file_rpc_daemon_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_rpc_daemon_service_proto_goTypes = []any{
	(*RestartRequest)(nil),  // 0: daemon.RestartRequest
	(*RestartResponse)(nil), // 1: daemon.RestartResponse
	(*StatusRequest)(nil),   // 2: daemon.StatusRequest
	(*StatusResponse)(nil),  // 3: daemon.StatusResponse
}
var file_rpc_daemon_service_proto_depIdxs = []int32{
	0, // 0: daemon.ZapretDaemon.Restart:input_type -> daemon.RestartRequest
	2, // 1: daemon.ZapretDaemon.GetStatus:input_type -> daemon.StatusRequest
	1, // 2: daemon.ZapretDaemon.Restart:output_type -> daemon.RestartResponse
	3, // 3: daemon.ZapretDaemon.GetStatus:output_type -> daemon.StatusResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_rpc_daemon_service_proto_init() }
func file_rpc_daemon_service_proto_init() {
	if File_rpc_daemon_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_daemon_service_proto_rawDesc), len(file_rpc_daemon_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpc_daemon_service_proto_goTypes,
		DependencyIndexes: file_rpc_daemon_service_proto_depIdxs,
		MessageInfos:      file_rpc_daemon_service_proto_msgTypes,
	}.Build()
	File_rpc_daemon_service_proto = out.File
	file_rpc_daemon_service_proto_goTypes = nil
	file_rpc_daemon_service_proto_depIdxs = nil
}
